# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='村名')),
                ('people_nums', models.IntegerField(max_length=11, verbose_name='人口数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '村数据',
                'verbose_name_plural': '村数据',
            },
        ),
    ]
