# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='people_nums',
            field=models.IntegerField(verbose_name='人口数量'),
        ),
    ]
