# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentIntention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='专业方向')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '专业方向',
                'verbose_name_plural': '专业方向',
            },
        ),
        migrations.CreateModel(
            name='PersonnelInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('group', models.CharField(max_length=4, verbose_name='组数')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('degree_of_education', models.CharField(choices=[('cz', '初中及以下'), ('gz', '高中'), ('dz', '大专'), ('bk', '本科'), ('ss', '硕士'), ('bs', '博士')], max_length=5, verbose_name='文化程度')),
                ('political_status', models.CharField(choices=[('qz', '群众'), ('ty', '团员'), ('dy', '党员')], max_length=2, verbose_name='政治面貌')),
                ('school_major_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='在读院校和专业')),
                ('is_village_cadres', models.CharField(default='否', max_length=30, verbose_name='是否为村干部及职位')),
                ('is_village_backup_cadres', models.CharField(default='否', max_length=30, verbose_name='是否为村后备干部及职位')),
                ('is_local_talent', models.CharField(default='否', max_length=30, verbose_name='是否为乡土人才及技能')),
                ('is_career_creating_talent', models.CharField(default='否', max_length=30, verbose_name='是否创业人才及创业方向')),
                ('working_place', models.CharField(blank=True, max_length=30, null=True, verbose_name='务工地点')),
                ('working_years', models.CharField(choices=[('1', '1年以下'), ('1to5', '1-5年'), ('5', '5年以上')], max_length=4, verbose_name='务工年限')),
                ('working_position', models.CharField(choices=[('5', '5万以下'), ('5to8', '5-8万'), ('8to12', '8-12万'), ('12', '12万以上')], max_length=5, verbose_name='务工职位')),
                ('phone_num', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系方式')),
                ('health_status', models.CharField(choices=[('healthy', '健康'), ('unhealthy', '患有疾病'), ('disabled', '残疾')], max_length=9, verbose_name='健康状态')),
                ('is_basic_living_allowances', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=3, verbose_name='是否低保')),
                ('is_rural_social_endowment_insurance', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=3, verbose_name='是否农保')),
                ('is_medical_insurance', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=3, verbose_name='是否参加医保')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('employment_intention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.EmploymentIntention', verbose_name='就业意向')),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='省份(直辖市)')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '省份(城市)',
                'verbose_name_plural': '省份(城市)',
            },
        ),
        migrations.AddField(
            model_name='personnelinformation',
            name='permanent_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.Province', verbose_name='常住地'),
        ),
    ]
