# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelinformation',
            name='working_position',
            field=models.CharField(blank=True, choices=[('5', '5万以下'), ('5to8', '5-8万'), ('8to12', '8-12万'), ('12', '12万以上')], max_length=5, null=True, verbose_name='务工职位'),
        ),
        migrations.AlterField(
            model_name='personnelinformation',
            name='working_years',
            field=models.CharField(blank=True, choices=[('1', '1年以下'), ('1to5', '1-5年'), ('5', '5年以上')], max_length=4, null=True, verbose_name='务工年限'),
        ),
    ]
