# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_auto_20171207_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('householder', models.CharField(max_length=20, verbose_name='户主')),
                ('is_poor_households', models.CharField(choices=[('yes', '是'), ('no', '否')], default='no', max_length=3, verbose_name='是否为贫困户')),
                ('causes_of_poverty', models.CharField(blank=True, max_length=100, null=True, verbose_name='致贫原因')),
                ('per_capita_arable_land_area', models.FloatField(default=0, verbose_name='人均耕地面积(亩)')),
                ('per_capita_woodland_area', models.FloatField(default=0, verbose_name='人均林地面积(亩)')),
                ('per_capita_circulation_area', models.FloatField(default=0, verbose_name='人均已流转面积(亩)')),
                ('annual_income', models.IntegerField(default=0, verbose_name='年收入(元)')),
                ('medical_expenditure', models.IntegerField(default=0, verbose_name='医疗支出(元)')),
                ('education_expenditure', models.IntegerField(default=0, verbose_name='教育支出(元)')),
                ('living_production_expenditure', models.IntegerField(default=0, verbose_name='生活生产支出(元)')),
            ],
        ),
        migrations.AddField(
            model_name='personnelinformation',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.Family', verbose_name='所在户(户主)'),
        ),
    ]
