# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_auto_20171208_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='务工行业')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '务工行业',
                'verbose_name_plural': '务工行业',
            },
        ),
        migrations.AlterField(
            model_name='family',
            name='annual_income',
            field=models.IntegerField(default=0, verbose_name='年收入(万元)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='education_expenditure',
            field=models.IntegerField(default=0, verbose_name='教育支出(万元)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='living_production_expenditure',
            field=models.IntegerField(default=0, verbose_name='生活生产支出(万元)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='medical_expenditure',
            field=models.IntegerField(default=0, verbose_name='医疗支出(万元)'),
        ),
        migrations.AlterField(
            model_name='personnelinformation',
            name='working_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.WorkingIndustry', verbose_name='务工行业'),
        ),
        migrations.AlterField(
            model_name='personnelinformation',
            name='working_position',
            field=models.CharField(blank=True, choices=[('lb', '老板'), ('zcgb', '中层干部'), ('ybgr', '一般工人'), ('w', '无')], default='wbgr', max_length=30, null=True, verbose_name='务工职位'),
        ),
        migrations.AlterField(
            model_name='personnelinformation',
            name='working_years',
            field=models.CharField(blank=True, choices=[('1', '1年以下'), ('1to5', '1-5年(不含)'), ('5', '5年及以上')], default='1to5', max_length=4, null=True, verbose_name='务工年限'),
        ),
    ]
