# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_auto_20171214_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': '常住地', 'verbose_name_plural': '常住地'},
        ),
        migrations.AddField(
            model_name='employmentintention',
            name='filter_name',
            field=models.CharField(default='', max_length=20, verbose_name='英文缩写(用于筛选)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='filter_name',
            field=models.CharField(default='1', max_length=20, verbose_name='英文缩写(用于筛选)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workingindustry',
            name='filter_name',
            field=models.CharField(default='1', max_length=20, verbose_name='英文缩写(用于筛选)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=20, verbose_name='常住地'),
        ),
    ]
