# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_auto_20171215_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentintention',
            options={'verbose_name': '就业意向', 'verbose_name_plural': '就业意向'},
        ),
        migrations.AlterField(
            model_name='employmentintention',
            name='name',
            field=models.CharField(max_length=20, verbose_name='就业意向'),
        ),
    ]
