# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0010_auto_20171215_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelinformation',
            name='is_basic_living_allowances',
            field=models.CharField(choices=[('db', '低保'), ('wb', '五保'), ('w', '无')], default='w', max_length=3, verbose_name='最低保障'),
        ),
        migrations.AlterField(
            model_name='personnelinformation',
            name='working_years',
            field=models.CharField(blank=True, choices=[('1', '1年以下'), ('1to5', '1-5年(不含)'), ('5', '5年及以上'), ('w', '无')], default='1to5', max_length=4, null=True, verbose_name='务工年限'),
        ),
    ]
