# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0014_auto_20171219_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='annual_income',
            field=models.IntegerField(default=0, verbose_name='年收入(元)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='education_expenditure',
            field=models.IntegerField(default=0, verbose_name='教育支出(元)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='living_production_expenditure',
            field=models.IntegerField(default=0, verbose_name='生活生产支出(元)'),
        ),
        migrations.AlterField(
            model_name='family',
            name='medical_expenditure',
            field=models.IntegerField(default=0, verbose_name='医疗支出(元)'),
        ),
    ]
